In [2]:
import numpy as np
# create a null vector of size 10 butthe fifth value which is 1

vector= np.zeros(10)
vector[4]-1
vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#create a vector with values ranging from 10 to 49

r=np.arange(10,50)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#create a 3X3 matrix with values ranging from 0 to 8

matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#Find indices of non-zeroes elements from given

nonz=np.array([1,2,0,0,4,0])
print(nonz.nonzero())

(array([0, 1, 4], dtype=int64),)


In [8]:
#create a 10X10 array with random values and findmin and max
m=np.random.randint(1,1000,(10,10))
print(m)
print(m.max())
print(m.min())

[[725 400  89 953 145 965  49 468  48 704]
 [129 264 148 999 665  26 929 588 152 369]
 [135 494 282  70 991 972 767 262  30 252]
 [575 889 519  95 855 878 186 980 658 633]
 [415 553 508  71 183 659 756 476 868 204]
 [961 675 230 278 148 652 116 474 996 625]
 [400 397  59 874 439 540 526 197 205 528]
 [805 118 145 209 816 242 161 930 285 307]
 [617 796 962 358 689 968 463 514 556 855]
 [834 495  42 951 136 412 576 222 857 555]]
999
26


In [9]:
#create a random vector of size 30 and find the mean value
mn=np.random.randint(0,100,(3,10))
print(mn)
print(mn.mean())

[[72 83 80 12 22 47 89 51 97 48]
 [64 61 22 29 26 68 22 11 51 43]
 [62 37 10 43 52 38 19 61 89  9]]
47.266666666666666
